modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="http://maxhenkel.de"
displayURL="http://maxhenkel.de"
authors="${mod_vendor}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="http://maxhenkel.de/update/miningworld.json"
description=''' '''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"