modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension"
authors="${mod_vendor}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="http://maxhenkel.de/update/mining_dimension.json"
description=''' '''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"